Make hack/bootstrap-cluster.sh wait more calmly
Avoid looking at a screen like this while we wait:

  error: the server doesn't have a resource type "appproject"
  error: the server doesn't have a resource type "appproject"
  error: the server doesn't have a resource type "appproject"
  ...
  Error from server (NotFound): namespaces "openshift-gitops" not found
  Error from server (NotFound): namespaces "openshift-gitops" not found
  Error from server (NotFound): namespaces "openshift-gitops" not found
  ...

Follow the style introduced by @Roming22 when waiting for the Argo
CD URl to work, and show an OK when it's done.